---
- name: install docker ce and compose
# install as per https://docs.docker.com/install/linux/docker-ce/centos/
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: install packages for docker ce
      yum: 
        name: "{{ item }}"
        state: latest
      loop: 
        - yum-utils
        - git
        - device-mapper-persistent-data
        - lvm2
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
    - name: Install Docker CE
      package:
        name: docker-ce
        state: latest
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Add user to docker group
      user:
        name: "{{ user }}"
        groups: docker
        append: yes
    - name: Install Extra Package for Enterprise Linux
      yum: 
        name: epel-release
        state: latest
    - name: Install python-pip
      yum:
        name: python-pip
        state: latest
    - name: Install Docker Compose
      yum:
        name: docker-compose
        state: latest
